-- Migration 0002: Ensure Row Level Security (RLS) is disabled on all tables
-- Run in Supabase SQL editor if any table defaults to auto-enabled RLS.

ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE setups DISABLE ROW LEVEL SECURITY;
ALTER TABLE setup_checklist_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE trades DISABLE ROW LEVEL SECURITY;
ALTER TABLE trade_exits DISABLE ROW LEVEL SECURITY;
ALTER TABLE trade_screenshots DISABLE ROW LEVEL SECURITY;
ALTER TABLE trade_timeline_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE trading_days DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
